{
  "openapi": "3.0.0",
  "info": {
    "title": "Product Management API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost/"
    }
  ],
  "paths": {
    "/api/products": {
      "get": {
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Get all products"
      },
      "post": {
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            },
            "description": "Created"
          }
        },
        "description": "Create a new product",
        "requestBody": {
          "$ref": "#/components/requestBodies/ProductInput"
        }
      }
    },
    "/api/products/{product_id}": {
      "delete": {
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "description": "Delete a product"
      },
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            },
            "description": "OK"
          }
        },
        "description": "Get a product by ID"
      },
      "put": {
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Product"
                }
              }
            },
            "description": "OK"
          }
        },
        "description": "Update a product",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductInput"
              }
            }
          },
          "required": true
        }
      }
    }
  },
  "components": {
    "requestBodies": {
      "ProductInput": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProductInput"
            }
          }
        },
        "required": true
      }
    },
    "schemas": {
      "Product": {
        "properties": {
          "description": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          }
        },
        "required": [
          "id",
          "name",
          "price"
        ],
        "type": "object"
      },
      "ProductInput": {
        "properties": {
          "description": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          }
        },
        "required": [
          "name",
          "price"
        ],
        "type": "object"
      }
    }
  }
}
