from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, price=None, stock=0):  # noqa: E501
        """ProductInput - a model defined in OpenAPI

        :param name: The name of this ProductInput.  # noqa: E501
        :type name: str
        :param description: The description of this ProductInput.  # noqa: E501
        :type description: str
        :param price: The price of this ProductInput.  # noqa: E501
        :type price: float
        :param stock: The stock of this ProductInput.  # noqa: E501
        :type stock: int
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'price': float,
            'stock': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'stock': 'stock'
        }

        self._name = name
        self._description = description
        self._price = price
        self._stock = stock

    @classmethod
    def from_dict(cls, dikt) -> 'ProductInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductInput of this ProductInput.  # noqa: E501
        :rtype: ProductInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProductInput.


        :return: The name of this ProductInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductInput.


        :param name: The name of this ProductInput.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductInput.


        :return: The description of this ProductInput.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductInput.


        :param description: The description of this ProductInput.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductInput.


        :return: The price of this ProductInput.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductInput.


        :param price: The price of this ProductInput.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501
        if price is not None and price < 0:  # noqa: E501
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `0`")  # noqa: E501

        self._price = price

    @property
    def stock(self) -> int:
        """Gets the stock of this ProductInput.


        :return: The stock of this ProductInput.
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock: int):
        """Sets the stock of this ProductInput.


        :param stock: The stock of this ProductInput.
        :type stock: int
        """
        if stock is not None and stock < 0:  # noqa: E501
            raise ValueError("Invalid value for `stock`, must be a value greater than or equal to `0`")  # noqa: E501

        self._stock = stock
